#tomcat端口
server:
  port: 8080

#数据源连接
spring:
  datasource:
    url: jdbc:mysql://10.36.137.13:3306/exam
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

#暴露、提供服务
dubbo:
  protocol:
    name: dubbo
    port: 20881
  application:
    name: stu_service
    owner: qzk
  registry:
    address: zookeeper://192.168.26.129:2181
  provider:
    timeout: 30000
  consumer:
    timeout: 30000
    check: false
    retries: 3

#配置别名
mybatis-plus:
  type-aliases-package: com.qf.entity
  mapper-locations: classpath:*.xml