#tomcat端口
server:
  port: 8081
#数据源
spring:
  datasource:
    url: jdbc:mysql://10.36.137.13:3306/exam
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
#暴露、提供服务
dubbo:
  protocol:
    name: dubbo
    port: 20880
  application:
    name: class_service
    owner: qzk
  registry:
    address: zookeeper://192.168.26.129:2181
  provider:
    timeout: 30000
  consumer:
      timeout: 30000
      check: false
      retries: 3

mybatis-plus:
  type-aliases-package: com.qf.entity
